CREATE USER balanx WITH PASSWORD 'balanx';
CREATE DATABASE balanx;
GRANT USAGE ON SCHEMA public TO balanx;
GRANT ALL PRIVILEGES ON DATABASE balanx TO balanx;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO balanx;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO balanx;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO balanx;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO balanx;
